Repository AY2021S1-CS2103T-W17-1/tp, pull requests merged in 2020-10, with the labels that each got.

#100 Update JavaDocs for Command and Logic
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBugDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/KanBugTrackerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/bug/BugTest.java
  src/test/java/seedu/address/model/bug/UniqueBugListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBugTest.java
  src/test/java/seedu/address/storage/JsonKanBugTrackerStorageTest.java
  src/test/java/seedu/address/testutil/TypicalBugs.java
Labels: type.Documentation

#120 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#121 Update documentation for Bug Priority feature in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#123 Update Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/KanbanBoardUI.puml
  docs/images/KanbanBoardUI.png
Labels: type.Documentation

#122 Add proposed Note feature implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/NoteAddActivityDiagram.puml
  docs/diagrams/NoteEditActivityDiagram.puml
  docs/images/NoteAddActivityDiagram.png
  docs/images/NoteEditActivityDiagram.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Documentation

#119 Update draft Developer Guide for proposed feature (search command)
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Documentation

#125 Fix UG mock-up images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui2.png
Labels: type.Documentation

#131 Add search command test
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/model/bug/BugContainsQueryStringPredicateTest.java
Labels: type.Enhancement

#128 Branch edit tag
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/KanBugTrackerParser.java
  src/main/main.iml
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTagCommandParserTest.java
  src/test/test.iml
Labels: priority.High, type.Enhancement

#138 Update User Guide
  docs/UserGuide.md
  docs/images/HomeFolder.PNG
  docs/images/KanBugDownload.PNG
  docs/images/Ui3.png
Labels: type.Documentation

#152 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation

#153 Update UG
  docs/UserGuide.md
  docs/images/HomeFolder.png
  docs/images/KanBugDownload.png
  docs/images/Ui3.png
  docs/images/Ui4.png
Labels: type.Documentation

#155 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTagByStateSequenceDiagram.puml
  docs/diagrams/AddTagClassDiagram.puml
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/diagrams/EditTagByStateSequenceDiagram.puml
  docs/diagrams/EditTagClassDiagram.puml
  docs/diagrams/EditTagSequenceDiagram.puml
  docs/images/AddTagByStateSequenceDiagram.png
  docs/images/AddTagClassStructure.png
  docs/images/AddTagSequenceDiagram.png
  docs/images/EditTagByStateSequenceDiagram.png
  docs/images/EditTagClassStructure.png
  docs/images/EditTagSequence.png
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
Labels: type.Documentation

#157 Update User Guide Skeleton
  docs/UserGuide.md
Labels: type.Documentation

#159 Make two Ui windows more consistent
  src/main/java/seedu/address/ui/BugCard.java
  src/main/java/seedu/address/ui/BugCardKanban.java
  src/main/resources/view/BugListCard.fxml
  src/main/resources/view/BugListPanelKanban.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/KanbanPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#160 Update UG based on tutor feedback
  docs/UserGuide.md
Labels: type.Documentation

#163 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#164 Fix exit on pressing Esc key
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement

#165 Update Help Window and User Guide formatting
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement

#166 Update UG & Add search command test
  docs/UserGuide.md
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: type.Documentation, type.Enhancement

#168 Update HelpWindow and User Guide to reflect Switch command
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation

#169 Remove DG [Proposed] tag for implemented features
  docs/DeveloperGuide.md
Labels: type.Documentation

#170 Update Ui images in UG and descriptions
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui2.png
  docs/images/Ui3.png
  docs/images/Ui4.png
Labels: type.Documentation

#176 Update User Guide
  docs/UserGuide.md
  docs/images/HomeFolder.png
  docs/images/Ui5.png
Labels: type.Documentation
