Repository AY2021S1-CS2103T-W17-1/tp, pull requests merged in 2020-11, with the labels that each got.

#219 Update section 2.1 of UG
  docs/UserGuide.md
Labels: type.Documentation

#220 Modify KanBugTrackerParser to prevent extra arguments for single word commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/KanBugTrackerParser.java
  src/test/java/seedu/address/logic/parser/KanBugTrackerParserTest.java
Labels: type.Bug

#221 Modify AddTagCommandParser to accept multiple tags
  src/main/java/seedu/address/logic/commands/AddTagByStateCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTagByStateCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTagByStateCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: type.Enhancement

#222 Update PPP for Kishen
  docs/team/kishenkumarrrrr.md
Labels: type.Documentation

#224 Update Sample Data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug

#225 Fix bug displaying wrong message for move command
  src/main/java/seedu/address/logic/commands/MoveCommand.java
  src/test/java/seedu/address/logic/commands/MoveCommandTest.java
Labels: type.Bug

#226 Change Bug#isSameBug to compare only the name.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MoveCommand.java
  src/main/java/seedu/address/model/bug/Bug.java
  src/test/java/seedu/address/logic/commands/MoveCommandTest.java
  src/test/java/seedu/address/model/bug/BugTest.java
Labels: type.Bug, type.Documentation

#227 Change default view into Kanban View
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, type.Documentation

#228 Fix bug dealing with index over MAX_INT
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: type.Bug

#230 Fix UG bugs from PE-D
  docs/UserGuide.md
Labels: type.Documentation

#232 Remove italics from UG
  docs/UserGuide.md
Labels: type.Documentation

#233 Correct UG Command Summary Order
  docs/UserGuide.md
  docs/team/the-reefshark.md
Labels: type.Documentation

#234 Update PPP for rogerlys
  docs/team/rogerlys.md
Labels: type.Documentation

#235 Update PPP for Duy part
  docs/team/duynguyen24501.md
Labels: type.Documentation

#237 Update some diagrams inherited from AB3
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#238 Update UG and minor refactoring
  docs/UserGuide.md
  docs/images/EditExample1.png
  docs/images/EditExample2.png
  docs/images/EditExample3.png
  docs/images/EditExample4.png
  docs/images/EditExample5.png
  docs/images/EditExample6.png
  docs/images/HelpExample1.png
  docs/images/HelpExample2.png
  docs/images/KanbanViewDelete.png
  docs/images/ListExample1.png
  docs/images/ListExample2.png
  docs/images/ListViewDelete.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/bug/Name.java
  src/main/java/seedu/address/model/bug/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedBug.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/model/bug/NameTest.java
Labels: type.Documentation, type.Refactoring

#239 Fix error message bug
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/MoveCommandParser.java
Labels: type.Bug

#240 Improve code quality in main
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/bug/Bug.java
  src/main/java/seedu/address/model/bug/Priority.java
  src/main/java/seedu/address/ui/BugCard.java
  src/main/java/seedu/address/ui/BugCardKanban.java
  src/main/java/seedu/address/ui/KanbanPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BugListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/KanbanPanel.fxml
  src/test/java/seedu/address/model/bug/PriorityTest.java
Labels: type.Refactoring

#241 Update Non-Functional Requirement, Glossary and add more Diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/SearchCommandClassDiagram.puml
  docs/images/SearchCommandClassDiagram.png
Labels: type.Documentation

#242 Divide BugCard's constructor into smaller chunks
  src/main/java/seedu/address/ui/BugCard.java
Labels: type.Refactoring

#244 Add Screen shots for UG
  docs/UserGuide.md
  docs/images/addExample1.png
  docs/images/addExample2.png
  docs/images/deleteCommandExample1.png
  docs/images/deleteCommandExample2.png
Labels: type.Documentation

#245 Make BugCard extend BugCardKanban
  src/main/java/seedu/address/ui/BugCard.java
  src/main/java/seedu/address/ui/BugCardKanban.java
Labels: type.Refactoring

#246 Branch refactor code
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/commands/ModifyTagUtility.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/model/bug/State.java
  src/test/java/seedu/address/logic/commands/AddTagByStateCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTagByStateCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/address/logic/commands/ModifyTagUtilityTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/KanBugTrackerParserTest.java
  src/test/java/seedu/address/model/bug/StateTest.java
Labels: type.Refactoring

#247 Improve code quality
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/KanbanPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/MoveCommandTest.java
Labels: type.Refactoring

#249 Refactor some of Main classes & Fix typos in DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/ui/BugCardKanban.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: type.Documentation, type.Refactoring

#252 Fix trailing zeroes issue of index
  src/main/java/seedu/address/commons/util/StringUtil.java
Labels: type.Bug

#251 fix documentation
  docs/UserGuide.md
  docs/team/rogerlys.md
Labels: type.Documentation

#253 Add manual testing guide in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#254 Format User Guide and redo introduction
  docs/UserGuide.md
Labels: type.Documentation

#255 Refactor Search & Move command
  src/main/java/seedu/address/logic/commands/MoveCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/MoveCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: type.Refactoring

#258 Refactor predicate test
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/bug/BugContainsQueryStringPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalBugs.java
Labels: type.Refactoring

#259 Branch update documentation
  docs/UserGuide.md
  docs/images/addTagAdded1.PNG
  docs/images/addTagMain.PNG
  docs/images/editTagEdited1.PNG
  docs/images/editTagMain.PNG
Labels: type.Documentation

#260 Refactor renaming to adhere code quality
  src/test/java/seedu/address/logic/LogicManagerListTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/KanBugTrackerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/bug/BugContainsQueryStringPredicateTest.java
  src/test/java/seedu/address/model/bug/BugTest.java
  src/test/java/seedu/address/model/bug/UniqueBugListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBugTest.java
  src/test/java/seedu/address/storage/JsonKanBugTrackerStorageTest.java
  src/test/java/seedu/address/testutil/TypicalBugs.java
Labels: type.Refactoring

#263 Update search use case in DG & highlight part in PPP
  docs/DeveloperGuide.md
  docs/team/duynguyen24501.md
Labels: type.Documentation

#264 Fix bug in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#265 Update UG,DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/NoteAddActivityDiagram.puml
  docs/diagrams/NoteEditActivityDiagram.puml
  docs/images/NoteAddActivityDiagram.png
  docs/images/NoteEditActivityDiagram.png
  docs/images/addTagAdded1.png
  docs/images/addTagMain.png
  docs/images/editTagEdited1.png
  docs/images/editTagMain.png
  docs/team/the-reefshark.md
Labels: type.Documentation

#269 Branch update documentation
  docs/DeveloperGuide.md
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/diagrams/EditTagActivityDiagram.puml
  docs/diagrams/EditTagSequenceDiagram.puml
  docs/images/AddTagSequenceDiagram.png
  docs/images/EditTagActivityDiagram.png
  docs/images/EditTagSequenceDiagram.png
Labels: type.Documentation

#272 Fix typos in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#273 Update UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/MoveMain.png
  docs/images/MoveMoved.png
Labels: type.Documentation

#278 Make small change in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#282 Update UG in save feature & Update PPP
  docs/UserGuide.md
  docs/team/phongtran98.md
Labels: type.Documentation

#283 Add PR links in PPP
  docs/team/duynguyen24501.md
Labels: type.Documentation

#284 Update ug
  docs/UserGuide.md
Labels: type.Documentation

#285 Fix bug in Ui images
  docs/UserGuide.md
  docs/images/ClearExample1.png
  docs/images/ClearExample2.png
  docs/images/ListExample1.png
  docs/images/ListExample2.png
  docs/images/MoveMain.png
  docs/images/MoveMoved.png
  docs/images/SearchExample1.png
  docs/images/SearchExample2.png
  docs/images/SwitchExample1.png
Labels: type.Documentation

#286 Capitalize the column title in the UI
  src/main/java/seedu/address/ui/KanbanPanel.java
Labels: type.Bug

#287 Remove header from Ui screenshots
  docs/images/MoveMain.png
  docs/images/MoveMoved.png
  docs/images/Ui.png
  docs/images/Ui2.png
  docs/images/Ui3.png
  docs/images/Ui4.png
  docs/images/addTagAdded1.png
  docs/images/addTagMain.png
  docs/images/editTagEdited1.png
  docs/images/editTagMain.png
Labels: type.Documentation

#288 Update PPP
  docs/team/phongtran98.md
Labels: type.Documentation

#293 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#294 Fix some typos in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#295 Fix typos in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#296 Branch update documentation
  docs/DeveloperGuide.md
Labels: type.Documentation

#299 Add reuse code's authors
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Documentation
